'use client';
import Link from 'next/link';
import type { Cart } from '@/shared/types';
import { date, Evidence, Header, Icon, money, ProductThumb, StatusBar, unit } from './ui';
import { useAppState } from './use-app-state';

export function CartPage() {
  const { state, setState, busy, error, request } = useAppState();
  async function update(productId: string, quantity: number) {
    const result = await request<{ cart: Cart }>('/api/cart', { productId, quantity }, 'Обновляем корзину');
    if (result) setState(prev => prev ? { ...prev, cart: result.cart } : prev);
  }
  return <div className="app-shell"><Header state={state} active="cart"/><main className="cart-main"><Link href="/" className="back-link">← Вернуться к подбору</Link><div className="cart-title"><div><span className="eyebrow">ПОДТВЕРЖДЁННЫЕ ПОЗИЦИИ</span><h1>Сохранённая корзина</h1></div><Icon name="bag" size={35}/></div>{state && <StatusBar state={state}/>}<div className="mode-notice">Это корзина прототипа, сохранённая для этой сессии. Интеграция с личным кабинетом ekt.kz не подключена. Заказ не оформляется.</div>{error && <div role="alert" className="error-banner">{error}</div>}{!state && !error && <p role="status">Загружаем корзину…</p>}{state?.cart.lines.length === 0 && <div className="cart-empty"><Icon name="bag" size={48}/><h2>Начнём с вашего подбора</h2><p>После проверки и подтверждения предложения товары появятся здесь.</p><Link className="button primary" href="/">Подобрать оборудование <Icon name="chevron" size={17}/></Link></div>}{state && state.cart.lines.length > 0 && <><p className="microcopy">Цены и остатки зафиксированы {date(state.cart.updatedAt)}. Это сохранённый состав, а не обещание актуальной доступности или резерв товара.</p><div className="cart-layout"><section className="cart-lines" aria-label="Товары в корзине">{state.cart.lines.map(line => <article key={line.product.id} className="cart-item"><div className="cart-item-top"><ProductThumb product={line.product}/><div><span className="sku">{line.product.sku}</span><h2>{line.product.name}</h2><p className="muted">{money(line.product.priceMinor)} / {unit(line.product)}</p></div><strong>{money(line.lineTotalMinor)}</strong></div><div className="cart-item-bottom"><div className="quantity-control"><button aria-label={`Уменьшить количество ${line.product.sku}`} disabled={!!busy || line.quantity <= 1} onClick={() => update(line.product.id, line.quantity - 1)}>−</button><span aria-label="Количество">{line.quantity}</span><button aria-label={`Увеличить количество ${line.product.sku}`} disabled={!!busy} onClick={() => update(line.product.id, line.quantity + 1)}>+</button></div><button className="text-button" disabled={!!busy} onClick={() => update(line.product.id, 0)}>Удалить</button></div><Evidence product={line.product}/></article>)}</section><aside className="cart-summary"><h2>Состав подтверждён</h2><p>Позиций: {state.cart.lines.length}</p><div className="proposal-total"><span>Итого</span><strong>{money(state.cart.totalMinor)}</strong></div><p className="muted">Корзина сохранена на сервере. Она останется доступной после обновления страницы в этой сессии.</p><Link href="/" className="button secondary full"><Icon name="plus" size={18}/>Добавить позиции</Link><div className="proposal-note"><Icon name="shield" size={18}/><span>Стоимость и наличие повторно проверяются при изменении количества.</span></div></aside></div></>}<p role="status" aria-live="polite" className="operation-status">{busy}</p></main></div>;
}
